# Generated by Django 4.2.7 on 2023-12-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Imagen',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='Precio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
